version: 2

general:
  build_dir: system

jobs:
  build:
    docker:
      - image: circleci/php:7.1-apache-node
      - image: circleci/mysql:5.7
        environment:
            - APP_NAME="WordPress License Server"
            - APP_ENV=production
            - APP_KEY=base64:B4Rt3hOfycCfbWoKqg7rLjbW/tsqxFGk6mpv/5FjevU=
            - APP_DEBUG=false
            - APP_URL=https://wpls.lab
            - DB_CONNECTION=sqlite_testing
            - DB_HOST=localhost
            - DB_PORT=
            - DB_DATABASE=circle_test
            - DB_USERNAME=root
            - DB_PASSWORD=
            - MYSQL_USER=root
            - MYSQL_PASSWORD=
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_DATABASE=circle_test
    working_directory: ~/laravel/system
    steps:
      - checkout
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev libpng-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "./system/composer.lock" }}
            - composer-v1-
      - run: cd system && composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "./system/composer.lock" }}
          paths:
            - vendor
      - restore_cache:
          keys:
            - node-v1-{{ checksum "./system/package.json" }}
            - node-v1-
      - run: cd system && yarn install
      - save_cache:
          key: node-v1-{{ checksum "./system/package.json" }}
          paths:
            - node_modules
      - run: cd system && touch storage/testing.sqlite
      - run: cd system && php artisan migrate --env=circleci --database=sqlite_testing --force
      - run: cd system && APP_ENV=circleci ./vendor/bin/phpunit